name: Manual trigger

on :
  workflow_dispatch:
    inputs:
      neededToPutIn:
        description: this is required field
        required: true
      thisCanOmit:
        description: this is an optional field
        required: false
        default: foo baa

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Print parameter from dispatch
        run: |
          echo "neededToPutIn ${{ github.event.inputs.neededToPutIn }}!"
          echo "thisCanOmit ${{ github.event.inputs.thisCanOmit }}!"

      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.1' # The Go version to download (if necessary) and use.
      - run: go version

      - name: Unit test
        run: go test

      