name: Pull request open

on:
  pull_request:
    types: [ opened, reopened ]
    branches:
      - master

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v2